### ISSUE TITLE
Database name in datasources.json does not match the docs

### ISSUE THREAD

**Issue by JonForest** [strongloop/loopback-getting-started#10]
In https://docs.strongloop.com/display/public/LB/Connect+your+API+to+a+data+source
It refers to the database as being called 'demo'

In the master branch for this code, the database in **datasources.json** is 'getting_started'

I suspect the notes need updating, but I'm not sure if they're in a github repo, so logging here.

**Comment by jakerella** [comment]
Nice catch! Our docs are maintained separately from our sample code sometimes... Perhaps @crandmck can coordinate those matching?

**Comment by crandmck** [comment]
@JonForest thanks for reporting.  I fixed it.
