### ISSUE TITLE
Step4 needs to have boot script root.js disabled

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-getting-started#11]
Per https://github.com/strongloop/loopback/issues/2012, there is a small problem with `step4`.  When I check out that release, it is not reflecting the change made in [Change or modify the default root route handler](https://docs.strongloop.com/display/LB/Add+a+static+web+page#Addastaticwebpage-Changeormodifythedefaultrootroutehandler) -- that is, `server/boot/root.js` should be renamed to `server/boot/root.js.disabled` or it could just be deleted (it doesn't matter, since it will work either way, but it might be more obvious if the file is there but just renamed with a non-.js extension).

**Comment by superkhau** [comment]
Closing as all steps have been removed as of 3.x upgrades. We'll need to upgrade the loopback.io docs instead.
