### ISSUE TITLE
Warning: please enter the name property again. The default value provided "" is not valid for type: string

### ISSUE THREAD

**Issue by bedrytskyi** [strongloop/loopback-getting-started#13]
After Property name -> Property type ->Required? -> Default value[leave blank for none] it throws me an error:

`Warning: please enter the name property again. The default value provided "" is not valid for type: string`

And asks me to select Property type once again! What is it? Why so rough start, guys?

**Comment by superkhau** [comment]
@crandmck ^ Is something wrong with the example?

**Comment by bedrytskyi** [comment]
I did everything step by step from http://docs.strongloop.com/display/LB/Getting+started+with+LoopBack and then from Getting started page http://loopback.io/getting-started/ (which are basically the same).

**Comment by bedrytskyi** [comment]
The problem is that "Default value[leave blank for none]" doesn't mention in any of your tutorials! I should leave blank or fill with some value?

**Comment by bedrytskyi** [comment]
Ok, I got it, I must set some value in that step. You should change a tutorial if this is new.

**Comment by superkhau** [comment]
@bedrytskyi Thanks for the feedback, @crandmck Can you look into this? Maybe we need to update the tutorial?

@davidcheung @deepakrkris I leave this up to you from here on since you are the repo owners.

**Comment by davidcheung** [comment]
related https://github.com/strongloop/generator-loopback/pull/200

**Comment by jannyHou** [comment]
@bedrytskyi I think the error msg has been fixed by the latest version of generator-loopback@1.23.2
I believe a blank default value will pass now.
 
Please reinstall your global generator-loopback to get it work.
If you don't prefer install it globally, you can update it inside strongloop

`DefaultValue prompt` is a feature we just improved, will add it in doc soon. Thanks for reminding!

---

Test from my local with the latest generator-loopback:
```
Let's add another CoffeeShops property.
Enter an empty property name when done.
? Property name: city
   invoke   loopback:property
? Property type: string
? Required? No
? Default value[leave blank for none]: 

Let's add another CoffeeShops property.
Enter an empty property name when done.
? Property name: name2
   invoke   loopback:property
? Property type: string
? Required? Yes
? Default value[leave blank for none]: 
```

**Comment by jannyHou** [comment]
@crandmck  I think we can add this in [doc](https://docs.strongloop.com/display/public/LB/Create+a+simple+API#CreateasimpleAPI-Createmodels) after property type selection:


You can define a "Default value" for your property, or leave it blank and click "Enter" if you don't need one:
```
? Default value[leave blank for none]: 
```

**Comment by crandmck** [comment]
Updated https://docs.strongloop.com/display/LB/Create+a+simple+API per @jannyHou comment ^
