### ISSUE TITLE
Model generator does not pass default empty string

### ISSUE THREAD

**Issue by stepanzarubin** [strongloop/loopback-getting-started#14]
Going through this tutorial https://docs.strongloop.com/display/public/LB/Create+a+simple+API
Model generator does not pass default empty string:

> Enter an empty property name when done.
> ? Property name: name
>    invoke   loopback:property
> ? Property type: string
> ? Required? Yes
> ? Default value[leave blank for none]:
> Warning: please enter the name property again. The default value provided "" is
> not valid for type: string

**Comment by davidcheung** [comment]
@stepanzarubin thanks for bringing this up, this issue should be fixed in  https://github.com/strongloop/generator-loopback/commit/9e6bff11c0586190466b89086d0c6c6ff2368419 but it is not yet published to npmjs

**Comment by jannyHou** [comment]
@bajtos Could you publish the [latest commit in generator-loopback](https://github.com/strongloop/generator-loopback/commits/master) to get this bug fixed in npm.js? Thanks!

**Comment by bajtos** [comment]
For posterity, here is the original issue: https://github.com/strongloop/generator-loopback/issues/213 I am waiting for our QA to verify the fix before making a new release.

This issue is a duplicate, I am closing it.
