### ISSUE TITLE
Add changes for phases (etc) to specific releases for use in Getting Started

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-getting-started#3]
Releases should have the following changes from previous:

- `step1` should include the following changes:
  - Default `/server/middleware.json`.  This is slightly different from the one in master.  Use the default scaffolded file created by `slc loopback`.
  - New `/server/config.json`.  Now has the "remoting" properties.
- `step4` should include all the changes in `master`.

When this is done, I can update http://docs.strongloop.com/display/LB/Add+a+static+web+page with the new version in http://docs.strongloop.com/display/LB/Copy+of+Add+a+static+web+page

**Comment by chandadharap** [comment]
https://groups.google.com/forum/#!topic/loopbackjs/VnniAgXNToY

**Comment by crandmck** [comment]
This is done.
