### ISSUE TITLE
Error: Cannot migrate models not attached to this datasource: CoffeeShop

### ISSUE THREAD

**Issue by pizza-hut** [strongloop/loopback-getting-started#45]
Followed the LB3 getting started but encountered above error...

datasource.js

`  "localDs": {
    "host": "127.0.0.1",
    "port": 3306,
    "url": "",
    "database": "demo",
    "password": "...",
    "name": "localDs",
    "user": "...",
    "connector": "mysql"
  }
}`

model-config.js
`  "Coffeeshop": {
    "dataSource": "localDs",
    "public": true
  }`

**Comment by dhmlau** [comment]
@pizza-hut, a quick question, do you have the database `demo` created? The database migration script expects the database exist and creates the table. Thanks.

**Comment by dhmlau** [comment]
FYI - Not sure if you're just starting out using LoopBack, if yes, I'd strongly recommend you to use LoopBack 4. LoopBack 4 is the current release, where LoopBack 3 will go end of life in Dec 2020. Also, LoopBack 4 has better extensibility and with more updated technology stacks. 

To get started with LoopBack 4, please try https://loopback.io/doc/en/lb4/todo-tutorial.html.

**Comment by pizza-hut** [comment]
Hi

Noted your advice on LB3 EOL.

Yes I do have the db. Very strange.
