### ISSUE TITLE
demo.strongloop.com 404

### ISSUE THREAD

**Issue by drkhannah** [strongloop/loopback-getting-started#6]
why cant we use this in step 2, I'm getting an error

**Comment by jakerella** [comment]
You can use `demo.strongloop.com` as a *mysql* server. Simply use the credentials on that [step in the guide](https://docs.strongloop.com/display/LB/Connect+your+API+to+a+data+source). Note that this subdomain _is not a web server_ so any requests not made directly to the mysql server (over port 3306) will fail. That is why you receive a `404` response if you try to hit the URL from a browser.
