### ISSUE TITLE
Error with slc start

### ISSUE THREAD

**Issue by drkhannah** [strongloop/loopback-getting-started#7]
I get this error when cloning the step4 branch and running slc start

Error: Cannot find module 'strong-debugger/package.json'

**Comment by superkhau** [comment]
@crandmck Is there an issue with the instructions?

**Comment by crandmck** [comment]
The pertinent steps are in https://docs.strongloop.com/display/LB/Add+a+custom+Express+route and they work for me.

@drkhannah Please follow those instructions.  If you still have a problem, please describe exactly the commands you entered and the results.
